/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package d3erp;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Neithan
 */
public class GUIFrame extends javax.swing.JFrame {

	/**
	 * Creates new form GUIFrame
	 */
	public GUIFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createIngredientDialog = new javax.swing.JDialog(this);
        ingredientNameField = new javax.swing.JTextField();
        ingredientAmountField = new javax.swing.JTextField();
        ingredientPriceField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ingredientCreateCancelButton = new javax.swing.JButton();
        ingredientCreateCreateButton = new javax.swing.JButton();
        editIngredientDialog = new javax.swing.JDialog();
        ingredientEditNameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ingredientEditUsableAmountField = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ingredientEditTable = new javax.swing.JTable();
        ingredientEditChangeButton = new javax.swing.JButton();
        ingredientEditCancelButton = new javax.swing.JButton();
        ingredientPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientListTable = new javax.swing.JTable();
        itemPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ingredientBuyPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ingredientBuySelect = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ingredientBuyAmount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ingredientBuyPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ingredientBuyTotal = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        createIngredientDialog.setTitle("Zutat anlegen");
        createIngredientDialog.setMinimumSize(new java.awt.Dimension(285, 210));
        createIngredientDialog.setModal(true);
        createIngredientDialog.setResizable(false);

        ingredientNameField.setInputVerifier(new StringVerifier());
        ingredientNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingredientNameFieldKeyPressed(evt);
            }
        });

        ingredientAmountField.setText("0");
        ingredientAmountField.setInputVerifier(new IntegerVerifier());
        ingredientAmountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingredientAmountFieldKeyPressed(evt);
            }
        });

        ingredientPriceField.setText("0,00");
        ingredientPriceField.setInputVerifier(new DoubleVerifier());
        ingredientPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingredientPriceFieldKeyPressed(evt);
            }
        });

        jLabel3.setText("<html><strong>Name:</strong>");

        jLabel4.setText("<html><strong>Menge:</strong>");

        jLabel5.setText("<html><strong>Preis:</strong>");

        jLabel6.setText("<html><strong>Info</strong>: Menge auf Null setzen, falls keine Menge<br>eingetragen werden soll.");

        ingredientCreateCancelButton.setText("Abbrechen");
        ingredientCreateCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientCreateCancelButtonActionPerformed(evt);
            }
        });

        ingredientCreateCreateButton.setText("Anlegen");
        ingredientCreateCreateButton.setMaximumSize(new java.awt.Dimension(85, 23));
        ingredientCreateCreateButton.setMinimumSize(new java.awt.Dimension(85, 23));
        ingredientCreateCreateButton.setPreferredSize(new java.awt.Dimension(85, 23));
        ingredientCreateCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientCreateCreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createIngredientDialogLayout = new javax.swing.GroupLayout(createIngredientDialog.getContentPane());
        createIngredientDialog.getContentPane().setLayout(createIngredientDialogLayout);
        createIngredientDialogLayout.setHorizontalGroup(
            createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createIngredientDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createIngredientDialogLayout.createSequentialGroup()
                        .addComponent(ingredientCreateCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ingredientCreateCancelButton)
                        .addGap(29, 29, 29))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createIngredientDialogLayout.createSequentialGroup()
                        .addGroup(createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ingredientNameField)
                            .addComponent(ingredientAmountField)
                            .addComponent(ingredientPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        createIngredientDialogLayout.setVerticalGroup(
            createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createIngredientDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(createIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientCreateCancelButton)
                    .addComponent(ingredientCreateCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        editIngredientDialog.setTitle("Zutat bearbeiten");
        editIngredientDialog.setMinimumSize(new java.awt.Dimension(380, 390));
        editIngredientDialog.setModal(true);
        editIngredientDialog.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                editIngredientDialogComponentShown(evt);
            }
        });

        ingredientEditNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingredientEditNameFieldKeyPressed(evt);
            }
        });

        jLabel7.setText("<html><strong>Name:</strong>");

        jLabel8.setText("<html><strong>Verfügbare Menge:</strong>");

        ingredientEditUsableAmountField.setText("0");

        jScrollPane2.setViewportView(ingredientEditTable);

        ingredientEditChangeButton.setText("Ändern");
        ingredientEditChangeButton.setMaximumSize(new java.awt.Dimension(85, 23));
        ingredientEditChangeButton.setMinimumSize(new java.awt.Dimension(85, 23));
        ingredientEditChangeButton.setPreferredSize(new java.awt.Dimension(85, 23));
        ingredientEditChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientEditChangeButtonActionPerformed(evt);
            }
        });

        ingredientEditCancelButton.setText("Abbrechen");
        ingredientEditCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientEditCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editIngredientDialogLayout = new javax.swing.GroupLayout(editIngredientDialog.getContentPane());
        editIngredientDialog.getContentPane().setLayout(editIngredientDialogLayout);
        editIngredientDialogLayout.setHorizontalGroup(
            editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editIngredientDialogLayout.createSequentialGroup()
                .addGroup(editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editIngredientDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editIngredientDialogLayout.createSequentialGroup()
                                .addGroup(editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ingredientEditNameField)
                                    .addComponent(ingredientEditUsableAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(editIngredientDialogLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(ingredientEditChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(ingredientEditCancelButton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        editIngredientDialogLayout.setVerticalGroup(
            editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editIngredientDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientEditNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientEditUsableAmountField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editIngredientDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientEditChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientEditCancelButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));

        ingredientPanel.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Zutaten");

        jButton1.setText("Hinzufügen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBar(null);

        ingredientListTable.setModel(new IngredientTableModel());
        TableColumn idColumn = ingredientListTable.getColumnModel().getColumn(0);
        idColumn.setPreferredWidth(120);
        TableColumn nameColumn = ingredientListTable.getColumnModel().getColumn(1);
        nameColumn.setPreferredWidth(300);
        TableColumn amountColumn = ingredientListTable.getColumnModel().getColumn(2);
        amountColumn.setPreferredWidth(180);
        ingredientListTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        ingredientListTable.getTableHeader().setReorderingAllowed(false);
        ingredientListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingredientListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ingredientListTable);

        javax.swing.GroupLayout ingredientPanelLayout = new javax.swing.GroupLayout(ingredientPanel);
        ingredientPanel.setLayout(ingredientPanelLayout);
        ingredientPanelLayout.setHorizontalGroup(
            ingredientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingredientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingredientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ingredientPanelLayout.setVerticalGroup(
            ingredientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingredientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        itemPanel.setVisible(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Gegenstände");

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(544, Short.MAX_VALUE))
        );

        ingredientBuyPanel.setVisible(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Zutateneinkauf");

        ingredientBuySelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setLabelFor(ingredientBuySelect);
        jLabel10.setText("Zutat:");

        jLabel11.setLabelFor(ingredientBuyAmount);
        jLabel11.setText("Menge:");

        ingredientBuyAmount.setText("0");

        jLabel12.setText("Einzelpreis:");

        ingredientBuyPrice.setText("0,00");

        jLabel13.setLabelFor(ingredientBuyTotal);
        jLabel13.setText("Gesamtpreis:");

        ingredientBuyTotal.setText("0,00");

        javax.swing.GroupLayout ingredientBuyPanelLayout = new javax.swing.GroupLayout(ingredientBuyPanel);
        ingredientBuyPanel.setLayout(ingredientBuyPanelLayout);
        ingredientBuyPanelLayout.setHorizontalGroup(
            ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingredientBuyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(ingredientBuyPanelLayout.createSequentialGroup()
                        .addGroup(ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(29, 29, 29)
                        .addGroup(ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ingredientBuySelect, 0, 119, Short.MAX_VALUE)
                            .addComponent(ingredientBuyAmount)
                            .addComponent(ingredientBuyPrice)
                            .addComponent(ingredientBuyTotal))))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        ingredientBuyPanelLayout.setVerticalGroup(
            ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingredientBuyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientBuySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ingredientBuyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ingredientBuyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ingredientBuyTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(435, Short.MAX_VALUE))
        );

        jMenu1.setMnemonic('d');
        jMenu1.setText("Datei");
        jMenu1.setToolTipText("");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('h');
        jMenuItem1.setText("Herstellen");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setMnemonic('b');
        jMenuItem2.setText("Beenden");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setMnemonic('l');
        jMenu3.setText("Lager");

        jMenuItem5.setText("Einkauf");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Verkauf");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu2.setMnemonic('s');
        jMenu2.setText("Stammdaten");

        jMenuItem3.setMnemonic('z');
        jMenuItem3.setText("Zutaten");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showIngredientPanel(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setMnemonic('g');
        jMenuItem4.setText("Gegenstände");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ingredientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 77, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ingredientBuyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 80, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingredientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(itemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ingredientBuyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ingredientPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
		D3erp.saveStore();
		System.exit(0);
	}//GEN-LAST:event_jMenuItem2ActionPerformed

	private void showIngredientPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showIngredientPanel
		ingredientPanel.setVisible(true);
		itemPanel.setVisible(false);

		this.validate();
	}//GEN-LAST:event_showIngredientPanel

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
		ingredientPanel.setVisible(false);
		itemPanel.setVisible(true);

		this.validate();
	}//GEN-LAST:event_jMenuItem4ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		createIngredientDialog.setVisible(true);
	}//GEN-LAST:event_jButton1ActionPerformed

	private void ingredientCreateCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientCreateCancelButtonActionPerformed
		createIngredientDialog.setVisible(false);
		ingredientNameField.setText("");
		ingredientAmountField.setText("0");
		ingredientPriceField.setText("0,00");
	}//GEN-LAST:event_ingredientCreateCancelButtonActionPerformed

	private void ingredientCreateCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientCreateCreateButtonActionPerformed
		createIngredientDialog.setVisible(false);

		Store store = Store.getInstance();
		String name = ingredientNameField.getText();
		int amount = Integer.parseInt(ingredientAmountField.getText());
		double price = Double.parseDouble(ingredientPriceField.getText().replace(',', '.'));
		int ingredientID = store.addIngredient(name);

		if (amount > 0)
			store.getIngredient(ingredientID).addStock(amount, price);

		ingredientListTable.setModel(new IngredientTableModel());

		TableColumn idColumn = ingredientListTable.getColumnModel().getColumn(0);
		idColumn.setPreferredWidth(120);
		TableColumn nameColumn = ingredientListTable.getColumnModel().getColumn(1);
		nameColumn.setPreferredWidth(300);
		TableColumn amountColumn = ingredientListTable.getColumnModel().getColumn(2);
		amountColumn.setPreferredWidth(180);

		ingredientListTable.validate();

		ingredientNameField.setText("");
		ingredientAmountField.setText("0");
		ingredientPriceField.setText("0,00");
	}//GEN-LAST:event_ingredientCreateCreateButtonActionPerformed

	private void ingredientListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredientListTableMouseClicked
		if (evt.getClickCount() == 2)
		{
			editIngredientDialog.setVisible(true);
		}
	}//GEN-LAST:event_ingredientListTableMouseClicked

	private void editIngredientDialogComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_editIngredientDialogComponentShown
		int row = ingredientListTable.getSelectedRow();
		int ingredientID = (int) ingredientListTable.getModel().getValueAt(row, 0);
		Store store = Store.getInstance();
		Ingredient ingredient = store.getIngredient(ingredientID);
		ingredientEditNameField.setText(ingredient.getName());
		ingredientEditUsableAmountField.setText(Integer.toString(ingredient.getTotalAmount()));

		ingredientEditTable.setModel(new IngredientStockTableModel(ingredientID));
	}//GEN-LAST:event_editIngredientDialogComponentShown

	private void ingredientEditCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientEditCancelButtonActionPerformed
		editIngredientDialog.setVisible(false);
		ingredientEditNameField.setText("");
		ingredientEditUsableAmountField.setText("0");
		ingredientEditTable.removeAll();
	}//GEN-LAST:event_ingredientEditCancelButtonActionPerformed

	private void ingredientEditChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientEditChangeButtonActionPerformed
		int row = ingredientListTable.getSelectedRow();
		int ingredientID = (int) ingredientListTable.getModel().getValueAt(row, 0);
		Store store = Store.getInstance();
		Ingredient ingredient = store.getIngredient(ingredientID);
		ingredient.setName(ingredientEditNameField.getText());

		ingredientListTable.getModel().setValueAt(ingredientEditNameField.getText(), row, 1);

		editIngredientDialog.setVisible(false);
		ingredientEditNameField.setText("");
		ingredientEditUsableAmountField.setText("0");
		ingredientEditTable.removeAll();
	}//GEN-LAST:event_ingredientEditChangeButtonActionPerformed

	private void ingredientEditNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingredientEditNameFieldKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER)
			ingredientEditChangeButton.doClick();
		else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
			ingredientEditCancelButton.doClick();
	}//GEN-LAST:event_ingredientEditNameFieldKeyPressed

	private void ingredientNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingredientNameFieldKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER)
			ingredientCreateCreateButton.doClick();
		else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
			ingredientCreateCancelButton.doClick();
	}//GEN-LAST:event_ingredientNameFieldKeyPressed

	private void ingredientAmountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingredientAmountFieldKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER)
			ingredientCreateCreateButton.doClick();
		else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
			ingredientCreateCancelButton.doClick();
	}//GEN-LAST:event_ingredientAmountFieldKeyPressed

	private void ingredientPriceFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingredientPriceFieldKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER)
			ingredientCreateCreateButton.doClick();
		else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
			ingredientCreateCancelButton.doClick();
	}//GEN-LAST:event_ingredientPriceFieldKeyPressed

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jMenuItem6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog createIngredientDialog;
    private javax.swing.JDialog editIngredientDialog;
    private javax.swing.JTextField ingredientAmountField;
    private javax.swing.JTextField ingredientBuyAmount;
    private javax.swing.JPanel ingredientBuyPanel;
    private javax.swing.JTextField ingredientBuyPrice;
    private javax.swing.JComboBox ingredientBuySelect;
    private javax.swing.JTextField ingredientBuyTotal;
    private javax.swing.JButton ingredientCreateCancelButton;
    private javax.swing.JButton ingredientCreateCreateButton;
    private javax.swing.JButton ingredientEditCancelButton;
    private javax.swing.JButton ingredientEditChangeButton;
    private javax.swing.JTextField ingredientEditNameField;
    private javax.swing.JTable ingredientEditTable;
    private javax.swing.JLabel ingredientEditUsableAmountField;
    private javax.swing.JTable ingredientListTable;
    private javax.swing.JTextField ingredientNameField;
    private javax.swing.JPanel ingredientPanel;
    private javax.swing.JTextField ingredientPriceField;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

	class IngredientTableModel extends AbstractTableModel
	{
		private String[] columnNames = {
			"Zutaten Nummer",
			"Name",
			"Menge"
		};
		private ArrayList<ArrayList<Object>> data;

		public IngredientTableModel()
		{
			this.data = new ArrayList<>();
			Store store = Store.getInstance();

			int i = 0;
			for (Map.Entry<Integer, Ingredient> entry : store.getIngredients().entrySet())
			{
				Integer key = entry.getKey();
				Ingredient ingredient = entry.getValue();

				ArrayList<Object> ingredientList = new ArrayList<>();
				ingredientList.add(ingredient.getId());
				ingredientList.add(ingredient.getName());
				ingredientList.add(ingredient.getTotalAmount());
				this.data.add(ingredientList);

				i++;
			}
		}

		@Override
		public int getColumnCount()
		{
			return this.columnNames.length;
		}

		@Override
		public int getRowCount()
		{
			return this.data.size();
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex)
		{
			return this.data.get(rowIndex).get(columnIndex);
		}

		@Override
		public String getColumnName(int column)
		{
			return this.columnNames[column];
		}

		@Override
		public void setValueAt(Object aValue, int rowIndex, int columnIndex)
		{
			this.data.get(rowIndex).set(columnIndex, aValue);
		}
	}

	class IngredientStockTableModel extends AbstractTableModel
	{
		private String[] columnNames = {
			"Menge",
			"Preis",
			"verbrauchte Menge"
		};
		private ArrayList<ArrayList<Object>> data;

		public IngredientStockTableModel(int ingredientID)
		{
			this.data = new ArrayList<>();
			Store store = Store.getInstance();
			Ingredient ingredient = store.getIngredient(ingredientID);

			for (int i = 0; i < ingredient.getInventory().size(); i++)
			{
				Stock stock = ingredient.getStock(i);
				ArrayList<Object> stockList = new ArrayList<>();
				stockList.add(stock.getAmount());
				stockList.add(stock.getPrice());

				int usedAmount = 0;
				for (int x = 0; x < stock.getUsedAmounts().size(); x++)
					usedAmount += stock.getUsedAmounts().get(x);

				stockList.add(usedAmount);
				this.data.add(stockList);
			}
		}

		@Override
		public int getColumnCount() {
			return this.columnNames.length;
		}

		@Override
		public int getRowCount()
		{
			return this.data.size();
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex)
		{
			return this.data.get(rowIndex).get(columnIndex);
		}

		@Override
		public String getColumnName(int column)
		{
			return this.columnNames[column];
		}
	}

	class IntegerVerifier extends InputVerifier
	{
		@Override
		public boolean verify(JComponent input)
		{
			JTextField field = (JTextField) input;
			try
			{
				Integer.parseInt(field.getText());
				return true;
			}
			catch (NumberFormatException nfex)
			{
				return false;
			}
		}
	}

	class DoubleVerifier extends InputVerifier
	{
		@Override
		public boolean verify(JComponent input)
		{
			JTextField field = (JTextField) input;
			String priceString = field.getText();
			try
			{
				double price = Double.parseDouble(priceString.replace(',', '.'));
				System.out.println(price);
				return true;
			}
			catch (NumberFormatException nfex)
			{
				return false;
			}
		}
	}

	class StringVerifier extends InputVerifier
	{
		@Override
		public boolean verify(JComponent input)
		{
			JTextField field = (JTextField) input;

			if (field.getText().length() > 0)
				return true;
			else
				return false;
		}
	}
}
